### ISSUE TITLE
Unhandled Java Exception in create_output():

### ISSUE THREAD

**Issue by florianbepunkt** [eemeli/pdf-form-fill#1]
Hi, I tried you library to fill out a pdf form, but the fill method crashes.

I have PDFtk installed.

fields(this.sourcePDF) works, but the fill method gives me 
```
fill(558): Error: Unhandled Java Exception in create_output():

    at Promise.then.then.then.then.catch.err (/Users/floriannorbertbepunkt/Dropbox/DropboxArbeit/CulinarioMortale/CulinarioMortale-Privat/Automatisierung-3-0/jarvis/node_modules/pdf-form-fill/index.js:148:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Error: Unhandled Java Exception in create_output():

    at Promise.then.then.then.then.catch.err (/Users/floriannorbertbepunkt/Dropbox/DropboxArbeit/CulinarioMortale/CulinarioMortale-Privat/Automatisierung-3-0/jarvis/node_modules/pdf-form-fill/index.js:148:40)
    at process._tickCallback (internal/process/next_tick.js:109:7)

```
here's my code…

```
import fs from 'fs';
const { fields, fill } = require('pdf-form-fill')

fields(this.sourcePDF)
.then(shape => console.log(shape))
.catch(err => console.error(err))

const output = fs.createWriteStream('./result.pdf')
fill(this.sourcePDF, data)
.then(stream => stream.pipe(output))
.catch(err => console.error(err))
```

**Comment by eemeli** [comment]
The error is a Java Exception, which means that it's coming from pdftk. Debugging it without access to the pdf file you're using and the data you're writing is rather difficult.

As one thought, have you verified that your node process has write access to the directory where you're writing the `result.pdf`? And for a second thought, if you're running this in a macOS environment, did you install PDFtk-server using the link from the home page (which mostly doesn't work), or the one mentioned [here](https://stackoverflow.com/a/33248310)?

**Comment by eemeli** [comment]
Closing as out of scope.
